/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsArtistSlugRouteImport } from './routes/artists.$artistSlug'
import { Route as ArtworksIndexRouteImport } from './routes/artworks.index'
import { Route as ArtworksArtworkSlugRouteImport } from './routes/artworks.$artworkSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const ArtistsArtistSlugRoute = ArtistsArtistSlugRouteImport.update({
  id: '/$artistSlug',
  path: '/$artistSlug',
  getParentRoute: () => ArtistsRoute,
} as any)
const ArtworksIndexRoute = ArtworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtworksRoute,
} as any)
const ArtworksArtworkSlugRoute = ArtworksArtworkSlugRouteImport.update({
  id: '/$artworkSlug',
  path: '/$artworkSlug',
  getParentRoute: () => ArtworksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/artworks': typeof ArtworksRouteWithChildren
  '/editorial': typeof EditorialRoute
  '/shows': typeof ShowsRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/artworks/$artworkSlug': typeof ArtworksArtworkSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/artworks/': typeof ArtworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editorial': typeof EditorialRoute
  '/shows': typeof ShowsRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/artworks/$artworkSlug': typeof ArtworksArtworkSlugRoute
  '/artists': typeof ArtistsIndexRoute
  '/artworks': typeof ArtworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/artworks': typeof ArtworksRouteWithChildren
  '/editorial': typeof EditorialRoute
  '/shows': typeof ShowsRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/artworks/$artworkSlug': typeof ArtworksArtworkSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/artworks/': typeof ArtworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/artworks'
    | '/editorial'
    | '/shows'
    | '/artists/$artistSlug'
    | '/artworks/$artworkSlug'
    | '/artists/'
    | '/artworks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editorial'
    | '/shows'
    | '/artists/$artistSlug'
    | '/artworks/$artworkSlug'
    | '/artists'
    | '/artworks'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/artworks'
    | '/editorial'
    | '/shows'
    | '/artists/$artistSlug'
    | '/artworks/$artworkSlug'
    | '/artists/'
    | '/artworks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  ArtworksRoute: typeof ArtworksRouteWithChildren
  EditorialRoute: typeof EditorialRoute
  ShowsRoute: typeof ShowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/artists/$artistSlug': {
      id: '/artists/$artistSlug'
      path: '/$artistSlug'
      fullPath: '/artists/$artistSlug'
      preLoaderRoute: typeof ArtistsArtistSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/artworks/': {
      id: '/artworks/'
      path: '/'
      fullPath: '/artworks/'
      preLoaderRoute: typeof ArtworksIndexRouteImport
      parentRoute: typeof ArtworksRoute
    }
    '/artworks/$artworkSlug': {
      id: '/artworks/$artworkSlug'
      path: '/$artworkSlug'
      fullPath: '/artworks/$artworkSlug'
      preLoaderRoute: typeof ArtworksArtworkSlugRouteImport
      parentRoute: typeof ArtworksRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsArtistSlugRoute: typeof ArtistsArtistSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistSlugRoute: ArtistsArtistSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface ArtworksRouteChildren {
  ArtworksArtworkSlugRoute: typeof ArtworksArtworkSlugRoute
  ArtworksIndexRoute: typeof ArtworksIndexRoute
}

const ArtworksRouteChildren: ArtworksRouteChildren = {
  ArtworksArtworkSlugRoute: ArtworksArtworkSlugRoute,
  ArtworksIndexRoute: ArtworksIndexRoute,
}

const ArtworksRouteWithChildren = ArtworksRoute._addFileChildren(
  ArtworksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  ArtworksRoute: ArtworksRouteWithChildren,
  EditorialRoute: EditorialRoute,
  ShowsRoute: ShowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
